### ISSUE TITLE
Dynamic index ( proxmox backup client for hosts / files ) support

### ISSUE THREAD

**Issue by tizbac** [tizbac/pmoxs3backuproxy#2]
Support is planned to add next weekend, if anyone wants to do it before, write it here please thanks

**Comment by abbbi** [comment]
i messed around a little bit and at least got the proxmox-backup-client to a state where i was able to push indexes (without chunks) and list the snapshots. The fix for snapshot listing is at:

https://github.com/abbbi/pmoxs3backuproxy/tree/snapshots_list

**Comment by tizbac** [comment]
Ok i will implement dynamic index on sunday probably unless you already WIP or done

**Comment by abbbi** [comment]
not working on this atm

**Comment by abbbi** [comment]
i think i got it :)

**Comment by tizbac** [comment]
I also implemented incremental backup when using dynamic index ( a bit tricky to do ) so we can consider this closed
