### ISSUE TITLE
Sync from S3 remote to PBS

### ISSUE THREAD

**Issue by abbbi** [tizbac/pmoxs3backuproxy#47]
I think it should be possible to use the s3 proxy as remote in PBS.

Lets say you use S3 as second backup target for weekly jobs or something (for offsite copies), then
it should be possible to sync back the backups if you lose your local PBS.

Currently it fails because it expects a little bit more information during datastore status as it seems:

```
2024-08-19T23:27:40+02:00: Starting datastore sync job 's3store:backups:test::s-5bd88e98-4c78'
2024-08-19T23:27:40+02:00: sync datastore 'test' from 's3store/backups'
2024-08-19T23:27:40+02:00: TASK ERROR: invalid type: null, expected a sequence
```

I guess it expects a little bit more information (counts and gc info?) and needs the namespace backend:

` /api2/json/admin/datastore/backups/namespace? Method: GET`

**Comment by tizbac** [comment]
https://lists.proxmox.com/pipermail/pbs-devel/2024-August/010381.html are you trying with that patch set? or it is in released version already?

**Comment by tizbac** [comment]
Can also reply to my email so i give you my telegram username and we can coordinate better? thanks

**Comment by abbbi** [comment]
im currently only investigating the pull mechanism where you can sync remotes to local PBS storage.
Push would be awesome too, but i dont have that version running.

**Comment by abbbi** [comment]
See #48
