### ISSUE TITLE
GC: indexed folder not processed correctly?

### ISSUE THREAD

**Issue by abbbi** [tizbac/pmoxs3backuproxy#57]
hi,

while playing around with GC i noticed i allways get the following output:

`1 object hashes found`

It appears to me as if the ChecksumSHA256 value  that is used to fill the object hashes list:

` knownHashes[object.ChecksumSHA256] = true`

is not set for any of the files.

It seems minio only calculates the checksum and fills this object info if PutObjectRequest is set accordingly, then the objects also have the x-amz-content-sha256 info set.

The current implementation does not do so, but sets a specified user metadata tag for the csum found in
the objects UserMetadata map (object.UserMetadata["X-Amz-Meta-Csum"])

**Comment by abbbi** [comment]
change in this PR would be my way to solve this:

 https://github.com/tizbac/pmoxs3backuproxy/pull/58

**Comment by tizbac** [comment]
I had that doubt when i did it, but not having other S3 service at hand and finding no docs about sha256 being computed or not i took it for good 
If missing yes, only way is metadata
