### ISSUE TITLE
Backups to AWS S3 fail: readfrom tcp [..]: http: ContentLength=859699 with Body length 0

### ISSUE THREAD

**Issue by stevenwhayes** [tizbac/pmoxs3backuproxy#62]
I'd like to try this out but I'm not sure how to invoke this.  What is the SSL cert supposed to be? The utility will not start without one.

**Comment by stevenwhayes** [comment]
Ok I think I get the SSL piece now, that is PBS standard stuff

Maybe incorporate some of the discussion here into your README

https://forum.proxmox.com/threads/s3-backup-support.152901/

**Comment by stevenwhayes** [comment]
here's the AWS IAM policy that worked for me if you want to add it in to the README:

`
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowSpecificBucketAccess",
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket",
        "s3:GetObject",
        "s3:PutObject"
      ],
      "Resource": [
        "arn:aws:s3:::yourbucketname",
        "arn:aws:s3:::yourbucketname/*"
      ]
    },
    {
      "Sid": "AllowListAllMyBuckets",
      "Effect": "Allow",
      "Action": "s3:ListAllMyBuckets",
      "Resource": "*"
    }
  ]
}
`

**Comment by stevenwhayes** [comment]
I am hitting a "real" error now, none of the backups will complete.  They all fail with something like this

ERROR: backup write data failed: command error: write_data upload error: pipelined request failed: Put "http://mybucket.s3.dualstack.us-east-2.amazonaws.com/chunks/6b/cb/52c4d184c27f6e999bb37e22c032adc7d65eb85769a5beac2f8b963d60c9": readfrom tcp <proxmox IP>:37040->3.5.131.60:80: http: ContentLength=2167529 with Body length 0{"data":{"digest":"6bcb52c4d184c27f6e999bb37e22c032adc7d65eb85769a5beac2f8b963d60c9","offset":0,"size":4194304,"chunk_is_known":false}}

**Comment by abbbi** [comment]
can you provide a comlete log with probably debug info?
Which Proxmox version are you using this with? Personally i have not verified this proxy still works with Proxmox 8.3

**Comment by stevenwhayes** [comment]
I'm on proxmox pve 8.2.2.  I tried a couple more things, one using IAM credentials with full admin on the account to rule anything out there.  It still errored.  I tried a different VM, and interestingly enough it failed the first time, but then completed the second time.  I have not tried all my VM's yet, do you know if there are any limits to disk size or things like that?  I've attached the debug log, it only contains the fail not the success I was not capturing the log on that one.
[pmoxs3proxy-debug.zip](https://github.com/user-attachments/files/17963007/pmoxs3proxy-debug.zip)


I'd really like to get this tool working, it is a very good idea and fills a very needed gap with proxmox, thank you for writing it.

**Comment by abbbi** [comment]
hi,

there is really not much to see in the Log. It fails while writing an non-existant junk to the bucket.
During upload it is verified the object does not already exist and if not, upload is attempted. It fails here:

https://github.com/tizbac/pmoxs3backuproxy/blob/master/cmd/pmoxs3backuproxy/main.go#L942

it seems to have successfully wrote the chunks before, so the general functionality seems to be given.
It also detects some chunks already existant.

Unfortunately the error output does not give any detail upon why the write operation failed. You could
enable logging on the AWS bucket and check why it fails to write sometimes. Maybe some Quotas beeing hit or an issue with the uplink connection?

**Comment by abbbi** [comment]
ive pushed the following commit to branch errcode, which i think should then give more detail on why the upload failed:

https://github.com/tizbac/pmoxs3backuproxy/commit/cdd17144e5270f8e496c0d36dea9bc8ae7cb45dd

beware its untested. Could you try with the version from this branch and see if it returns an detailed error message on what happened?

**Comment by stevenwhayes** [comment]
I gave that version a try, the backup more progress than earlier today but ultimately error'ed out.  I've attached the log.  I'm sure it would work with minio locally, unfortunately that does not help my use case.  I've tried to backup proxmox direct to S3 with FUSE as well and it has similar but worse issues.  If I can get a baseline backup to complete, seems like there is better chance the incrementals will then complete, but I fear this just may not be possible without being on a very fast connection to S3 or maybe even from inside AWS.  If the underlying S3 protocols allow retry / retransmit maybe that could help?
[pmoxs3backuproxy-testing.zip](https://github.com/user-attachments/files/17964281/pmoxs3backuproxy-testing.zip)

**Comment by abbbi** [comment]
not much to see from the advanced log output.. I still think your uplink is at fault here. Of course if a baseline backup makes it through, incrementals are more likely to work because less data is transferred. You could try to see if loggin on the S3 bucket logs some more information.

**Comment by stevenwhayes** [comment]
I have good Internet, gigabit up and down but it is residential. One thing I'm noticing is the fail messages are always reporting an HTTP connection. HTTP tends to be subject to more aggressive traffic shaping, especially on residential networks. If the connection can be forced to HTTPS, that may make a difference. I understand if you don't want to spend more time on this though, I'm not much of a go coder but I can try to figure that out.

**Comment by abbbi** [comment]
the proxy supports ssl:

```
  -usessl
        Enable SSL connection to the endpoint, for use with cloud S3 providers
```

**Comment by stevenwhayes** [comment]
Ah thank you, I must have missed that.  I enabled the SSL connection, and now the backups are completing as expected.  I'm going to close the issue, thank you for your help with troubleshooting this and for creating the tool!
